### ISSUE TITLE
wm keybind problem

### ISSUE THREAD

**Issue by solitudealma** [System64fumo/syslock#1]
I was testing syslock in nixos hyprland. Since it didn't cover the bar, I tried to switch workspaces and found that it didn't disable this operation. I successfully switched workspaces. Swaylock directly treats all input as the input password. I think it should be handled like this

**Comment by System64fumo** [comment]
Correct, syslock does not do that by default *yet* due to it not making use of the session lock protocol
You can enable it by passing the -e launch argument however it's very unfinished and experimental.

I don't really know how to finish it so i can't really put more work into the session lock protocol, If you do feel free to contribute but for now this sadly remains a problem..

Current issues with the session lock protocol implementation in syslock:
Duplicate rendering - The GTK window still renders under the locked session thing
Non functional touch gestures - Touch gestures do not work when the SL proto is enabled
Single monitor support - Technically easy to fix i'm just lazy
Occasional crashes - Not fully stable yet

**Comment by solitudealma** [comment]
> Correct, syslock does not do that by default _yet_ due to it not making use of the session lock protocol You can enable it by passing the -e launch argument however it's very unfinished and experimental.
> 
> I don't really know how to finish it so i can't really put more work into the session lock protocol, If you do feel free to contribute but for now this sadly remains a problem..
> 
> Current issues with the session lock protocol implementation in syslock: Duplicate rendering - The GTK window still renders under the locked session thing Non functional touch gestures - Touch gestures do not work when the SL proto is enabled Single monitor support - Technically easy to fix i'm just lazy Occasional crashes - Not fully stable yet

OK, I understand. I hope more people can join in. You can go to [this](https://www.reddit.com/r/unixporn) to promote it a little bit.

**Comment by System64fumo** [comment]
Ah, I don't use reddit so can't really.
But thanks i guess.
